### ISSUE TITLE
Weather-card: missing info

### ISSUE THREAD

**Issue by bouwew** [bramkragten/custom-ui#14]
Hi,

Thank you very much for creating this beautiful weather-card!

But, in my opinion, if you don't mind me saying, it is not "finished". It is missing the name of the city/station and optionally the name of the service-provider in/on the card.  Would you consider adding at least the city name?

This is how it look on my system:
![image](https://user-images.githubusercontent.com/11290930/51437275-50f1a380-1c9c-11e9-9c6a-fd802e9dd620.png)

**Comment by bramkragten** [comment]
Is added in version 1.1.0

**Comment by bouwew** [comment]
Thanks!

Unfortunately, I see no name:
![image](https://user-images.githubusercontent.com/11290930/51487002-723cb780-1da2-11e9-9dab-207d29ee1f8e.png)

This is in my configuration.yaml:
```
weather:
  - platform: buienradar
    name: 'groningen'
    latitude: 53.13
    longitude: 6.58
    forecast: True
 ```

Also, the minutes in the times of sunrise and sunset are displayed double.
Update: sorry, I see the last digits are seconds, this might be a coincident for my location today.
