### ISSUE TITLE
Swiper card doesn't work after a second time

### ISSUE THREAD

**Issue by gbdavidx** [bramkragten/custom-ui#15]
Weird issue, swiper card will work great after a frech cache-clean, but once its loaded i just displays the second card right below the top card

this is my config
```

title: My Awesome Home

resources:
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.2
  type: js
- url: /local/custom_ui/card-modder.js
  type: module
- url: /local/custom_ui/weather-card.js
  type: js
- url: /local/custom_ui/layout-card.js
  type: js
- url: /local/mini-media-player-bundle.js?v=0.9.8
  type: module
- url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.min.js
  type: module
- url: /local/custom-lovelace/swipe-card/swipe-card.js?v=1.1.0
  type: module
  
views:
  - id: 0
    name: Home
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: entities
            title: Whose Home
            show_header_toggle: false
            entities:
              - input_boolean.david_occupancy
          - type: horizontal-stack
            cards:
             - type: light
               entity: light.23460a
             - type: light
               entity: light.2349a5
             - type: light
               entity: light.dining_room
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.thermostat_temperature
                name: Home Temperature
              - type: sensor
                entity: sensor.thermostat_humidity
          - type: horizontal-stack
            cards:
              - type: sensor
                entity:  sensor.tautulli
                name: Streams from Plex
              - type: sensor
                entity:  sensor.tautulli.lan_bandwidth
            name: Home Humidity
          - break
          - type: horizontal-stack
            cards:
             - type: custom:swipe-card
               path: '/local/custom-lovelace/swipe-card'
               cards:
                 - type: custom:upcoming-media-card
                   entity: sensor.plex_recently_added
                   image_style: fanart
                   title: Movies Onboard
                 - type: custom:upcoming-media-card
                   entity: sensor.sonarr_upcoming_media
                   image_style: fanart
                   title: Upcoming TV

```

this is the only related error i get, Sun Jan 20 2019 12:10:29 GMT-0800 (Pacific Standard Time)

http://192.168.1.214:8123/lovelace/0:0:0 Uncaught
