### ISSUE TITLE
Picture-elements: Cannot read property 'states' of undefined

### ISSUE THREAD

**Issue by IDmedia** [bramkragten/custom-ui#3]
I'm getting this error when trying to put a picture-elements card in the swipe-card. Is this a known issue?
Works great with sensors though...

```
22af5b1c2d5fbf8c18791.chunk.js:3767
Uncaught (in promise) TypeError: Cannot read property 'states' of undefined
```

```
             - type: vertical-stack
                cards:
                  - id: 5164373434
                    type: custom:swipe-card
                    parameters:
                      spaceBetween: 8
                      scrollbar:
                        hide: false
                        draggable: true
                        snapOnRelease: true
                    cards:
                      - type: picture-elements
                        title: First Floor Vacuum
                        image: /local/images/xiaomi_vacuum.jpg?v=29
                        elements: 
                          - type: image
                            tap_action:
                              action: none
                            hold_action:
                              action: none
                            entity: vacuum.vaccum_2nd_floor
                            image: /local/images/xiaomi_vacuum.png?v=7
                            style:
                              left: 43%
                              top: 38%
                      - type: picture-elements
                        title: Second Floor Vacuum
                        image: /local/images/xiaomi_vacuum.jpg?v=29
                        elements: 
                          - type: image
                            tap_action:
                              action: none
                            hold_action:
                              action: none
                            entity: vacuum.vaccum_2nd_floor
                            image: /local/images/xiaomi_vacuum.png?v=7
                            style:
                              left: 43%
                              top: 38%
```

Everything works when changing "type: custom:swipe-card" to something else such as "type: horizontal-stack" so it seems it doesn't handle the picture-elements.
