### ISSUE TITLE
Custom element doesn't exist: weather card

### ISSUE THREAD

**Issue by dominikheinz** [bramkragten/custom-ui#39]
Currently the weather card doesn't work at all. I followed the installation steps as explained in the guide, however in the UI I am prompted with the following error message:

![image](https://user-images.githubusercontent.com/32770080/57659923-748e8000-75e4-11e9-8edb-a60ec7a4d684.png)

I am using Firefox 66.0.5 (64-bit) and I tried the fixes suggested in the other issues such as setting `javascript.options.dynamicImport` to `true` in the `about:config`. 
This didn't fix the problem.
I also tried the same thing in Chrome, the problem is the same.

How can I fix this? I would really love to use this card, but currently its unusable.

**Comment by bramkragten** [comment]
The weather card works, your setup is just not right.

Please share your complete config including paths you placed the files and resources config.

**Comment by dominikheinz** [comment]
I placed all files from the repo under `/config/www/custom-lovelace/weather-card`, that includes:
`weather-card-editor.js`
`weather-card.js`
and a folder icons, with all the animated svg icons inside.
I added the resources to the very top of the `ui-lovelace.yaml` in the config folder:
```
resources:
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module

title: Home
views:
  - badges: []
    cards:
      - entity: light.nightlight
        name: Nightlight
        type: light
# ... more devices ...
```

The UI element has been added via the UI configuration by selecting manual card.

Did I link the resources section in the wrong file?
